const services = [
    {
      id: '1',
      name: 'Men\'s Classic Haircut',
      price: 25,
      duration: 30,
      rating: 4.7,
      ratingCount: '500+',
      description: 'A timeless haircut tailored to your individual style. Includes a hot towel finish.',
      image: require('@/assets/images/pfp.png'),
    },
    {
      id: '2',
      name: 'Men\'s Premium Haircut & Style',
      price: 40,
      duration: 45,
      rating: 4.9,
      ratingCount: '250+',
      description: 'A detailed haircut, styling with premium products, and a relaxing scalp massage.',
      image: require('@/assets/images/pfp.png'),
    },
    {
      id: '3',
      name: 'Beard Sculpting & Trim',
      price: 20,
      duration: 20,
      rating: 4.6,
      ratingCount: '300+',
      description: 'Expert beard shaping, trimming, and conditioning for a polished look.',
      image: require('@/assets/images/pfp.png'),
    },
    {
      id: '4',
      name: 'Men\'s Hair Color (Single Process)',
      price: 60,
      duration: 60,
      rating: 4.4,
      ratingCount: '150+',
      description: 'A single-process hair color application to cover grays or enhance your natural color.',
      image: require('@/assets/images/pfp.png'),
    },
    {
      id: '5',
      name: 'Hot Towel Shave & Facial',
      price: 35,
      duration: 40,
      rating: 4.8,
      ratingCount: '200+',
      description: 'A luxurious hot towel shave combined with a refreshing facial treatment.',
      image: require('@/assets/images/pfp.png'),
    },
  ];
  
  export default services;